project:
  type: website
  output-dir: docs

website:
  title: "haiiii :3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: tt1.qmd
        text: analysis 1
      - href: tt2.qmd
        text: analysis 2
format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true



