project:
  type: website
  output-dir: docs

website:
  title: "haiiii :3"
  navbar:
    left:
      - href: index.qmd
        text: Home Page
      - text: Data Viz
      - menu: 
        - href: tt1.qmd
          text: Viz1
        - href: tt2.qmd
          text: Viz2
 
format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true



